name: etiya_chatbot_domain
description: Includes domain layer abstraction (repositories)
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
